package com.privacyshield.bothub.data.model

import org.json.JSONObject
import java.util.UUID

data class MessageEntry(
    val id: String = UUID.randomUUID().toString(),
    val conversationId: String,
    val content: String,
    val senderType: SenderType,
    val status: MessageStatus = MessageStatus.SENT,
    val isAutoGenerated: Boolean = false,
    val timestamp: Long = System.currentTimeMillis()
) {
    fun toJson(): JSONObject = JSONObject().apply {
        put("id", id)
        put("conversationId", conversationId)
        put("content", content)
        put("senderType", senderType.name)
        put("status", status.name)
        put("isAutoGenerated", isAutoGenerated)
        put("timestamp", timestamp)
    }

    companion object {
        fun fromJson(json: JSONObject): MessageEntry = MessageEntry(
            id = json.optString("id").takeIf { it.isNotBlank() } ?: UUID.randomUUID().toString(),
            conversationId = json.optString("conversationId", ""),
            content = json.optString("content", ""),
            senderType = runCatching { SenderType.valueOf(json.optString("senderType")) }.getOrDefault(SenderType.SYSTEM),
            status = runCatching { MessageStatus.valueOf(json.optString("status")) }.getOrDefault(MessageStatus.SENT),
            isAutoGenerated = json.optBoolean("isAutoGenerated", false),
            timestamp = json.optLong("timestamp", System.currentTimeMillis())
        )
    }
}

enum class SenderType { BOT, CONTACT, SYSTEM }

enum class MessageStatus { SENDING, SENT, DELIVERED, READ, FAILED }
